// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.27;

import {Test} from "forge-std/Test.sol";
import {Poseidon2YulHash2} from "../src/Poseidon2YulHash2.sol";

/// @notice Byte-equal cross-check between `Poseidon2YulHash2` and the
///         Python reference `tools/v2_circuit_helpers.py::poseidon2_hash_2`,
///         which is itself byte-equal with the Noir primitive used in
///         `circuits/landmark_regions_v2/src/main.nr` for
///         `origin_face_id_i = poseidon2_hash_2(image_commit, i)`.
contract Poseidon2YulHash2Test is Test {
    Poseidon2YulHash2 internal hash2;

    function setUp() public {
        hash2 = new Poseidon2YulHash2();
    }

    /// Helper: invoke the Yul wrapper with two 32-byte big-endian Fields.
    function _hash2(bytes32 a, bytes32 b) internal view returns (bytes32 out) {
        bytes memory input = abi.encodePacked(a, b);
        (bool ok, bytes memory ret) = address(hash2).staticcall(input);
        require(ok, "hash2 staticcall failed");
        require(ret.length == 32, "hash2 wrong return length");
        assembly { out := mload(add(ret, 32)) }
    }

    /// Test vectors generated by:
    ///   python3 -c "import sys; sys.path.insert(0,'tools'); \
    ///     from v2_circuit_helpers import poseidon2_hash_2; \
    ///     print(hex(poseidon2_hash_2(a, b)))"
    function test_hash2_matches_python_reference() public view {
        assertEq(
            _hash2(bytes32(uint256(0)), bytes32(uint256(0))),
            bytes32(uint256(0x18dfb8dc9b82229cff974efefc8df78b1ce96d9d844236b496785c698bc6732e)),
            "hash_2(0,0)"
        );
        assertEq(
            _hash2(bytes32(uint256(1)), bytes32(uint256(0))),
            bytes32(uint256(0x02a04ea402711ced2d4bc39608cc5350a7db4af98ec2950d4d1ec30334d6c2b4)),
            "hash_2(1,0)"
        );
        assertEq(
            _hash2(bytes32(uint256(0)), bytes32(uint256(1))),
            bytes32(uint256(0x2ce0b6fcd20887e7855e149803d635bdb8cde2ea352a880a3d935124fd780f73)),
            "hash_2(0,1)"
        );
        assertEq(
            _hash2(bytes32(uint256(1)), bytes32(uint256(2))),
            bytes32(uint256(0x299bfccd7daf3c917e51291383929049ec0eaed800af245056cbf135f7dea636)),
            "hash_2(1,2)"
        );
        assertEq(
            _hash2(
                bytes32(uint256(0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef)),
                bytes32(uint256(0xfedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210))
            ),
            bytes32(uint256(0x22140067a80c1b9b849a4d8777dc0410c2d010ca5f37b713a18e34419ec6e2ae)),
            "hash_2(0x012..., 0xfed...)"
        );
        assertEq(
            _hash2(bytes32(uint256(0xdeadbeef)), bytes32(uint256(7))),
            bytes32(uint256(0x14260f836e270108be60b2372eaf5d985de56fc2c448d1885818b1170f5b39d7)),
            "hash_2(0xdeadbeef, 7)"
        );
    }

    /// Reject any calldata size other than exactly 64 bytes. The fallback
    /// has no padding/sentinel logic; non-canonical inputs MUST revert
    /// rather than be silently absorbed.
    function test_hash2_rejects_wrong_size() public {
        bytes memory empty;
        (bool ok1,) = address(hash2).staticcall(empty);
        assertFalse(ok1, "0 bytes must revert");

        (bool ok2,) = address(hash2).staticcall(new bytes(32));
        assertFalse(ok2, "32 bytes must revert");

        (bool ok3,) = address(hash2).staticcall(new bytes(63));
        assertFalse(ok3, "63 bytes must revert");

        (bool ok4,) = address(hash2).staticcall(new bytes(65));
        assertFalse(ok4, "65 bytes must revert");

        (bool ok5,) = address(hash2).staticcall(new bytes(96));
        assertFalse(ok5, "96 bytes must revert");
    }

    /// Non-canonical Fr inputs (greater than the modulus) MUST normalize to
    /// the same digest as their canonical-mod-PRIME representatives. This
    /// matches the Noir circuit semantics: `poseidon2_permutation` operates
    /// on canonical Fr elements.
    function test_hash2_reduces_inputs_mod_prime() public view {
        uint256 PRIME = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;
        bytes32 a = bytes32(uint256(7));
        bytes32 b = bytes32(uint256(13));
        bytes32 canonical = _hash2(a, b);
        bytes32 a_overflow = bytes32(PRIME + 7);
        bytes32 b_overflow = bytes32(PRIME + 13);
        bytes32 overflow_digest = _hash2(a_overflow, b_overflow);
        assertEq(canonical, overflow_digest, "non-canonical inputs reduce mod PRIME");
    }
}
