feature_id = ""
new_k = ""
new_lsh = ""
new_r = ""
next_pk_x = ""
next_pk_y = ""
old_c1_x = ""
old_c1_y = ""
old_chain_tip = ""
old_count = ""
old_ct_commit = ""
old_k = ""
old_lsh = ""
old_state_commit = ""
origin_face_id = ""
owner_sk = ""
palette_commit = ""
plaintext = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
type_idx = ""
